force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <description>BOM</description>
    <label>Arrival Airport</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Arrival_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date_Time__c</fullName>
    <label>Arrival Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <label>Available Seats</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Base_Fare__c.field-meta.xml
<CustomField>
    <fullName>Base_Fare__c</fullName>
    <label>Base Fare</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <description>IATA code of the departure airport, e.g. DEL</description>
    <inlineHelpText>IATA code of the departure airport, e.g. DEL</inlineHelpText>
    <label>Departure Airport</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time__c</fullName>
    <label>Departure Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Flight_Status__c.field-meta.xml
<CustomField>
    <fullName>Flight_Status__c</fullName>
    <label>Flight Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Departed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Arrived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Total_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Seats__c</fullName>
    <description>ex:180</description>
    <label>Total Seats</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FlightApiQueueable.cls
public with sharing class FlightApiQueueable implements Queueable, Database.AllowsCallouts {
    
    // Retry counter
    private Integer retryCount;
    // First execution
    public FlightApiQueueable(){
        this.retryCount = 0;
    }
    // Retry execution
    public FlightApiQueueable(Integer retryCount) {
        this.retryCount = retryCount;
    }
    
    public void execute(QueueableContext context) {
        try {
            // STEP 1: Call External Flight API
            String response = FlightApiClient.getFlights();
            
            // STEP 2: Convert API response into Flight records  
            List<Flight__c> apiFlights = FlightApiClient.buildFlightRecords(response);
            System.debug('Flights mapped from API: ' + apiFlights.size());
            if (apiFlights.isEmpty()) {
                System.debug('No flight records received.');
                return;
            }
            
            // STEP 3: Collect Flight Numbers
            Set<String> flightNumbers = new Set<String>();
            for (Flight__c flight : apiFlights) {
                if (String.isNotBlank(flight.Name)) {
                    flightNumbers.add(flight.Name);
                }
            }
            
            // STEP 4: Find Existing Salesforce Flights
            Map<String, Flight__c> existingFlights = new Map<String, Flight__c>();
            for (Flight__c existingFlight : [SELECT Id, Name 
                                             FROM Flight__c 
                                             WHERE Name IN :flightNumbers]){
                                                 existingFlights.put(existingFlight.Name, existingFlight);
                                             }
            
            // STEP 5: Prepare Insert and Update Lists
            List<Flight__c> recordsToInsert = new List<Flight__c>();
            List<Flight__c> recordsToUpdate =new List<Flight__c>();
            Integer skippedFlights = 0;
            
            // STEP 6: Process API Flight Records
            for (Flight__c apiFlight : apiFlights) {
                
                // Skip invalid flight timings
                if (
                    apiFlight.Departure_Date_Time__c == null ||
                    apiFlight.Arrival_Date_Time__c == null ||
                    apiFlight.Arrival_Date_Time__c <= apiFlight.Departure_Date_Time__c){
                        skippedFlights++;
                        System.debug('Skipping invalid flight timing: ' + apiFlight.Name);
                        continue;
                    }
                
                // UPDATE EXISTING FLIGHT
                if (existingFlights.containsKey(apiFlight.Name)){
                    Flight__c existingFlight = existingFlights.get(apiFlight.Name);
                    existingFlight.Departure_Airport__c = apiFlight.Departure_Airport__c;
                    existingFlight.Arrival_Airport__c = apiFlight.Arrival_Airport__c;
                    existingFlight.Departure_Date_Time__c = apiFlight.Departure_Date_Time__c;
                    existingFlight.Arrival_Date_Time__c = apiFlight.Arrival_Date_Time__c;
                    existingFlight.Flight_Status__c = apiFlight.Flight_Status__c;
                    recordsToUpdate.add(existingFlight);
                }
                
                // INSERT NEW FLIGHT
                else {
                    // Temporary defaults because
                    // Aviationstack does not provide
                    // these required Salesforce fields
                    
                    apiFlight.Total_Seats__c = 180;
                    apiFlight.Available_Seats__c = 180;
                    apiFlight.Base_Fare__c = 5000;
                    recordsToInsert.add(apiFlight);
                }
            }
            
            // STEP 7: Insert New Flights
            if (!recordsToInsert.isEmpty()) {
                insert recordsToInsert;
            }
            
            // STEP 8: Update Existing Flights
            if (!recordsToUpdate.isEmpty()) {
                update recordsToUpdate;
            }
            
            // STEP 9: Logging
            System.debug('New Flights Inserted: ' + recordsToInsert.size());
            System.debug('Existing Flights Updated: ' + recordsToUpdate.size());
            System.debug('Invalid Flights Skipped: ' + skippedFlights);
        }
        catch (Exception e) {
            System.debug('Flight API Queueable Error: ' + e.getMessage());
            
            // STEP 10: Retry Once If API Fails
            if (retryCount < 1) {
                System.debug('Flight API retry queued.');
                System.enqueueJob(new FlightApiQueueable(retryCount + 1));
            } else {
                System.debug('Flight API failed after retry.');
            }
        }
    }
}